"""empty message

Revision ID: 5b4e3684f03a
Revises: 
Create Date: 2021-10-21 00:03:26.300523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b4e3684f03a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('surname', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('permissions', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('status', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['id_event'], ['Event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Bought_Ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ticket'], ['Ticket.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reserved_Ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ticket'], ['Ticket.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    op.drop_table('Reserved_Ticket')
    op.drop_table('Bought_Ticket')
    op.drop_table('Ticket')
    op.drop_table('User')
    op.drop_table('Event')
    # ### end Alembic commands ###
